spring:
  application:
    name: Filmes API
  datasource:
    url: jdbc:h2:mem:filmes
    username: sa
    password: "1234"
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
